# Generated by Django 3.1.7 on 2021-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0004_auto_20210409_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
