# Generated by Django 3.1.7 on 2021-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0006_auto_20210409_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='edit_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
