# Generated by Django 3.1.7 on 2021-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0007_articles_edit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='edit_time',
        ),
        migrations.AddField(
            model_name='articles',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
