# Generated by Django 3.1.7 on 2021-05-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforum', '0009_remove_articles_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
